name: Serial OS Jobs with Concurrency

on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    concurrency:
      group: serial-os-job
    steps:
      - name: Run on Ubuntu
        run: echo "Running on Ubuntu"

  macos:
    runs-on: macos-latest
    needs: ubuntu
    concurrency:
      group: serial-os-job
    steps:
      - name: Run on macOS
        run: echo "Running on macOS"

  windows:
    runs-on: windows-latest
    needs: macos
    concurrency:
      group: serial-os-job
    steps:
      - name: Run on Windows
        run: echo "Running on Windows"
